
const presetColors = {
  "Blue (Default)": {
    "--sw-toolbar-btn-background-color": "#009EF7",
    "--sw-anchor-default-primary-color": "#f8f9fa",
    "--sw-anchor-default-secondary-color": "#b0b0b1",
    "--sw-anchor-active-primary-color": "#009EF7",
    "--sw-anchor-active-secondary-color": "#ffffff",
    "--sw-anchor-done-primary-color": "#90d4fa",
    "--sw-anchor-done-secondary-color": "#fefefe",
    "--sw-progress-color": "#009EF7",
    "--sw-loader-color": "#009EF7",
  },
  "Green": {
    "--sw-border-color": "#eeeeee",
    "--sw-toolbar-btn-color": "#ffffff",
    "--sw-toolbar-btn-background-color": "#008931",
    "--sw-anchor-default-primary-color": "#f8f9fa",
    "--sw-anchor-default-secondary-color": "#b0b0b1",
    "--sw-anchor-active-primary-color": "#78c043",
    "--sw-anchor-active-secondary-color": "#ffffff",
    "--sw-anchor-done-primary-color": "#588835",
    "--sw-anchor-done-secondary-color": "#c2c2c2",
    "--sw-anchor-disabled-primary-color": "#f8f9fa",
    "--sw-anchor-disabled-secondary-color": "#dbe0e5",
    "--sw-anchor-error-primary-color": "#dc3545",
    "--sw-anchor-error-secondary-color": "#ffffff",
    "--sw-anchor-warning-primary-color": "#ffc107",
    "--sw-anchor-warning-secondary-color": "#ffffff",
    "--sw-progress-color": "#78c043",
    "--sw-progress-background-color": "#f8f9fa",
    "--sw-loader-color": "#78c043",
    "--sw-loader-background-color": "#f8f9fa",
    "--sw-loader-background-wrapper-color": "rgba(255, 255, 255, 0.7)",
  },
  "Yellow": {
    "--sw-border-color": "#eeeeee",
    "--sw-toolbar-btn-color": "#ffffff",
    "--sw-toolbar-btn-background-color": "#e4a707",
    "--sw-anchor-default-primary-color": "#f8f9fa",
    "--sw-anchor-default-secondary-color": "#b0b0b1",
    "--sw-anchor-active-primary-color": "#fbbd19",
    "--sw-anchor-active-secondary-color": "#ffffff",
    "--sw-anchor-done-primary-color": "#e4a707",
    "--sw-anchor-done-secondary-color": "#dbe0e5",
    "--sw-anchor-disabled-primary-color": "#f8f9fa",
    "--sw-anchor-disabled-secondary-color": "#dbe0e5",
    "--sw-anchor-error-primary-color": "#dc3545",
    "--sw-anchor-error-secondary-color": "#ffffff",
    "--sw-anchor-warning-primary-color": "#ffc107",
    "--sw-anchor-warning-secondary-color": "#ffffff",
    "--sw-progress-color": "#fbbd19",
    "--sw-progress-background-color": "#f8f9fa",
    "--sw-loader-color": "#fbbd19",
    "--sw-loader-background-color": "#f8f9fa",
    "--sw-loader-background-wrapper-color": "rgba(255, 255, 255, 0.7)",
  },
  "Red": {
    "--sw-border-color": "#eeeeee",
    "--sw-toolbar-btn-color": "#ffffff",
    "--sw-toolbar-btn-background-color": "#f44336",
    "--sw-anchor-default-primary-color": "#f8f9fa",
    "--sw-anchor-default-secondary-color": "#b0b0b1",
    "--sw-anchor-active-primary-color": "#f44336",
    "--sw-anchor-active-secondary-color": "#ffffff",
    "--sw-anchor-done-primary-color": "#f8877f",
    "--sw-anchor-done-secondary-color": "#fefefe",
    "--sw-anchor-disabled-primary-color": "#f8f9fa",
    "--sw-anchor-disabled-secondary-color": "#dbe0e5",
    "--sw-anchor-error-primary-color": "#dc3545",
    "--sw-anchor-error-secondary-color": "#ffffff",
    "--sw-anchor-warning-primary-color": "#ffc107",
    "--sw-anchor-warning-secondary-color": "#ffffff",
    "--sw-progress-color": "#f44336",
    "--sw-progress-background-color": "#f8f9fa",
    "--sw-loader-color": "#f44336",
    "--sw-loader-background-color": "#f8f9fa",
    "--sw-loader-background-wrapper-color": "rgba(255, 255, 255, 0.7)",
  },
  "Lite Blue": {
    "--sw-border-color": "#eeeeee",
    "--sw-toolbar-btn-color": "#ffffff",
    "--sw-toolbar-btn-background-color": "#0cb6d8",
    "--sw-anchor-default-primary-color": "#f8f9fa",
    "--sw-anchor-default-secondary-color": "#b0b0b1",
    "--sw-anchor-active-primary-color": "#00d5ff",
    "--sw-anchor-active-secondary-color": "#ffffff",
    "--sw-anchor-done-primary-color": "#0cb6d8",
    "--sw-anchor-done-secondary-color": "#dbe0e5",
    "--sw-anchor-disabled-primary-color": "#f8f9fa",
    "--sw-anchor-disabled-secondary-color": "#dbe0e5",
    "--sw-anchor-error-primary-color": "#dc3545",
    "--sw-anchor-error-secondary-color": "#ffffff",
    "--sw-anchor-warning-primary-color": "#ffc107",
    "--sw-anchor-warning-secondary-color": "#ffffff",
    "--sw-progress-color": "#0dcaf0",
    "--sw-progress-background-color": "#f8f9fa",
    "--sw-loader-color": "#0dcaf0",
    "--sw-loader-background-color": "#f8f9fa",
    "--sw-loader-background-wrapper-color": "rgba(255, 255, 255, 0.7)",
  },
  "Dark": {
    "--sw-border-color": "#eeeeee",
    "--sw-toolbar-btn-color": "#ffffff",
    "--sw-toolbar-btn-background-color": "#0a2730",
    "--sw-anchor-default-primary-color": "#757575",
    "--sw-anchor-default-secondary-color": "#b0b0b1",
    "--sw-anchor-active-primary-color": "#000000",
    "--sw-anchor-active-secondary-color": "#ffffff",
    "--sw-anchor-done-primary-color": "#333333",
    "--sw-anchor-done-secondary-color": "#aaaaaa",
    "--sw-anchor-disabled-primary-color": "#f8f9fa",
    "--sw-anchor-disabled-secondary-color": "#dbe0e5",
    "--sw-anchor-error-primary-color": "#dc3545",
    "--sw-anchor-error-secondary-color": "#ffffff",
    "--sw-anchor-warning-primary-color": "#ffc107",
    "--sw-anchor-warning-secondary-color": "#ffffff",
    "--sw-progress-color": "#0a2730",
    "--sw-progress-background-color": "#f8f9fa",
    "--sw-loader-color": "#0a2730",
    "--sw-loader-background-color": "#f8f9fa",
    "--sw-loader-background-wrapper-color": "rgba(255, 255, 255, 0.7)",
  }
}